# Generated by Django 5.0.2 on 2024-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='course_name', max_length=150),
            preserve_default=False,
        ),
    ]
